contact_links:
  - name: Discuss Threadbare
    about: See previously-asked questions about Threadbare, and ask your own
    url: https://github.com/endlessm/threadbare/discussions/categories/q-a

  - name: Chat with the community
    about: Join us on Discord
    url: https://discord.gg/joinendless

  - name: Learn about Endless Access
    about: Visit our website
    url: https://www.endlessos.org/game-making
